apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudguard.fullname" . }}-api
  labels:
    app: api
    {{- include "cloudguard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: api
      {{- include "cloudguard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: api
        {{- include "cloudguard.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}/api:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloudguard.fullname" . }}-secrets
                  key: database-url
            - name: REDIS_URL
              value: "redis://{{ include "cloudguard.fullname" . }}-redis:6379/0"
            - name: ML_SERVICE_URL
              value: "http://{{ include "cloudguard.fullname" . }}-ml:8001"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloudguard.fullname" . }}-secrets
                  key: secret-key
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          {{- with .Values.resources.api }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudguard.fullname" . }}-api
  labels:
    app: api
    {{- include "cloudguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 8000
  selector:
    app: api
    {{- include "cloudguard.selectorLabels" . | nindent 4 }}
